export class Registration {
    constructor(
        public ID: number,
        public REFID?: number,
        public TITLE: string = 'novalue',
        public NAME?: string,
        public MOBILE?: string,
        public LINE?: string,
        public STATUS: string = 'verified',
        public DATEIN?: Date,
        public REGISTER?: string,
        public KACHART: string = 'redcross',
        public DATESYMPTOM?: Date,
        public DATEPOSITIVE?: Date,
        public TESTING: string = 'other',
        public TESTINGLOCATION?: string,
        public TESTINGREMARK?: string,
        public THAIID?: string,
        public GENDER: string = 'novalue',
        public AGE?: string,
        public BIRTHDATE?: Date,
        public WEIGHT?: number,
        public MARRIAGE: string = 'single',
        public DISEASE?: string,
        public HEALTH?: string,
        public HEALTHHOSPITAL?: string,
        public HEALTHPROJECT?: string,
        public RELATIVE?: string,
        public RELATIVEMOBILE?: string,
        public RELATIVEMOBILE2?: string,
        public HOMENO?: string,
        public HOMESOI?: string,
        public HOMEROAD?: string,
        public HOMESUBDISTRICT?: string,
        public HOMEDISTRICT?: string,
        public HOMEPROVINCE?: string,
        public HOMEPOSTAL?: string,
        public MOBILETYPE: string = 'android',
        public OFFICETHAIIDCOPY?: string,
        public OFFICECOVIDTEST?: string,
        public OFFICESTATUS?: string,
        public HI?: string,
        public HIDATE?: Date,
        public HISTATUS?: string,
        public CI?: string,
        public CIDATE?: Date,
        public CIO2?: string,
        public CISTATUS?: string,
        public PSY?: string
    ) {}
}